kernel_modules:
  - cramfs
  - freevxfs
  - hfs
  - hfsplus
  - jffs2
  - udf
  - usb-storage
  - afs
  - ceph
  - exfat
  - fscache
  - gfs2
  - nfsd
  - dccp
  - tipc
  - rds
  - sctp

network_kernel_parameters:
  - name: net.ipv4.ip_forward
    value: 0
  - name: net.ipv6.conf.all.forwarding
    value: 0
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.conf.default.send_redirects
    value: 0
  - name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
  - name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  - name: net.ipv4.conf.default.accept_redirects
    value: 0
  - name: net.ipv6.conf.all.accept_redirects
    value: 0
  - name: net.ipv6.conf.default.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.secure_redirects
    value: 0
  - name: net.ipv4.conf.default.secure_redirects
    value: 0
  - name: net.ipv4.conf.all.rp_filter
    value: 1
  - name: net.ipv4.conf.default.rp_filter
    value: 1
  - name: net.ipv4.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_source_route
    value: 0
  - name: net.ipv6.conf.all.accept_source_route
    value: 0
  - name: net.ipv6.conf.default.accept_source_route
    value: 0
  - name: net.ipv4.tcp_syncookies
    value: 1
  - name: net.ipv6.conf.all.accept_ra
    value: 0
  - name: net.ipv6.conf.default.accept_ra
    value: 0