crontab_files:
  - path: /etc/crontab
    mode: '0600'
  - path: /etc/cron.hourly
    mode: '0700'
  - path: /etc/cron.daily
    mode: '0700'
  - path: /etc/cron.weekly
    mode: '0700'
  - path: /etc/cron.monthly
    mode: '0700'
  - path: /etc/cron.d
    mode: '0700'